sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker
      script:
        - make b-lang-docker CURRENT_LANG=php
    - stage: test
      script: docker run --rm hongjianghuang/php:latest cat composer.json