sudo: true
dist: trusty

jobs:
  include:
    - stage: build php docker
      script:
        - echo "$DockerHubPassword" | docker login -u "$DockerHubAccount" --password-stdin
        - make b-lang-docker CURRENT_LANG=php
        - docker push hongjianghuang/php:latest
    - stage: run php test
      script:
        - docker run --rm hongjianghuang/php:latest