sudo: true
dist: trusty

jobs:
  include:
    - stage: build php docker
      script:
        - echo "$DockerHubAccount" | docker login -u "$DockerHubPassword" --password-stdin
        - make b-lang-docker CURRENT_LANG=php
        - docker push huanghongjiang/php:latest
    - stage: run php test
      script:
        - docker run --rm huanghongjiang/php:latest