sudo: true
dist: trusty

stages:
  - php-test
  - go-test
  - node-test

jobs:
  include:
    - stage: php-test
      script:
        - echo "$DockerHubPassword" | docker login -u "$DockerHubAccount" --password-stdin
        - make b-lang-docker CURRENT_LANG=php
        - docker push hongjianghuang/php:latest
        - docker run --rm hongjianghuang/php:latest
    - stage: go-test
      script:
        - echo "$DockerHubPassword" | docker login -u "$DockerHubAccount" --password-stdin
        - make b-lang-docker CURRENT_LANG=go
        - docker push hongjianghuang/go:latest
        - docker run --rm hongjianghuang/go:latest
    - stage: node-test
      script:
        - echo "$DockerHubPassword" | docker login -u "$DockerHubAccount" --password-stdin
        - make b-lang-docker CURRENT_LANG=node
        - docker push hongjianghuang/node:latest
        - docker run --rm hongjianghuang/node:latest